### ISSUE TITLE
Fix code scanning alert - Pinned-Dependencies - Release Action

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1004]
### Pinned Dependency Remediation

Under `Security > Code Scanning` there is a [pinned dependency issue](https://github.com/defenseunicorns/pepr/security/code-scanning/97) that needs to be addressed.

[File in question](https://github.com/defenseunicorns/pepr/blob/main/.github/workflows/release.yml)

### How to Remediate
[https://app.stepsecurity.io](https://app.stepsecurity.io/secureworkflow/defenseunicorns/pepr/release.yml/main?enable=pin) can be used to pin the dependencies in the file.

This tell us exactly which version of each dependency is installed at any time, and increases our [OpenSSF Scorecard Score](https://securityscorecards.dev/viewer/?uri=github.com/defenseunicorns/pepr). 

The Publish Package step in our SLSA [action](https://github.com/defenseunicorns/pepr/blob/main/.github/workflows/release.yml) process does not have a hash pinned to it.

Current Version:
```yaml
      - name: Publish package
        id: publish
        uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@v2.0.0
```

After Remediation
```yaml
      - name: Publish package
        id: publish
        uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@5a775b367a56d5bd118a224a811bba288150a563 # v2.0.0
```

### Definition of Done
- [ ] Update the dependency to be the pinned at that version
- [ ] Update all dependencies in the file that can be pinned
