### ISSUE TITLE
Pepr core is mutating secrets 

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/pepr#129]
Using Pepr `0.6.0` I noticed secrets were getting patched that were not part of any capability or module.  Creating a junk file of a specific size and then storing it in a secret while a pepr module is running creates a secret that appears to have been mutated.

I  suspect it is something to do with the encoding/decoding of the data and perhaps non UTF-8 encoded data?

 ```
$ dd if=/dev/urandom of=1000.k bs=1KB count=1
                                                                                                   
$ kubectl create secret generic test --from-file=foo=1000.k -n default
secret/test created

$ kubectl describe secret/test
Name:         test
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
foo:  1822 bytes 
```

Notice the `1822 bytes`, this will be `1000` bytes if a Pepr module is not running.

**Comment by jeff-mccoy** [comment]
There are a couple issues--first is checking for diffs when it shouldn't and this encoding issue that looks similar to https://github.com/rancher/rancher/issues/27439.

**Comment by rjferguson21** [comment]
FYI it seems like the existing ASCII check is not decoding strings that contain newlines.  So for example `id` vs `brokenid`: 
```
apiVersion: v1
kind: Secret
metadata:
  name: configclient
  namespace: podinfo
  labels:
    todo: createclient
data:
  brokenid: ZGV2XzAwZWI4OTA0LTViODgtNGM2OC1hZDY3LWNlYzBkMmUwN2FhNl9wb2RpbmZvCg==
  id: ZGV2XzAwZWI4OTA0LTViODgtNGM2OC1hZDY3LWNlYzBkMmUwN2FhNl9wb2RpbmZv
  name: cG9kaW5mbw==
  domain: YmlnYmFuZy5kZXY=
  realm: YmFieS15b2Rh
 ```
