### ISSUE TITLE
Allow deploy-time configurable `alwaysIgnore.namespaces`

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/pepr#1610]
### Is your feature request related to a problem? Please describe.

Currently on uds-core we set 2 namespaces to ignore by default. In some environments these namespaces should not really be ignored (one is a dev namespace) and in other namespaces additional namespaces may need to be ignored (i.e. additional "system namespaces"). Currently these are configured at build time and we have not found an obvious way to allow this to be configured at deploy time.

### Describe the solution you'd like

The current setting is templated into the webhook configuration under:
```yaml
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
```

It would be a relatively easy change to allow this to be configured in the helm chart to append to/modify the list here. In the case of uds-core we could default this list to including the dev-stack, but via overrides at deploy time it could be modified.

### Describe alternatives you've considered

1. Make this the module author's responsibility - rather than filtering out with the webhook config, the module code could filter based on namespace.
2. Identify an alternative path with zarf/etc that would be viable to modify this.
