### ISSUE TITLE
Examine unused `hash` property in Assets class.

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/pepr#1638]
### Describe what should be investigated or refactored

The `Assets` class has a property, `hash: string`, and a setter (`setHash()`) that appear unused. Hashing for assets appears to be generated by a call to `crypto.createHash("sha256").update(code).digest("hex")` and then passed to relevant consumers.

We should examine if this `hash` property is truly necessary on the Assets class. If it is not, remove it. If it is, address the unused code.

### Links to any relevant code

None.

### Additional context

None.

**Comment by cmwylie19** [comment]
I could be wrong, but I thought that hash was used in the command section of the controller pods:

```yaml
        - name: server
          image: ghcr.io/defenseunicorns/pepr/controller:v0.0.0-development
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - ea243bd3eab9e19651f4409b57f9cba2ff8f426d3df78207d96a2e85245ffb29 # Hash
```
