### ISSUE TITLE
GenericKind cannot be watched

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1838]
### Describe what should be investigated or refactored

```ts
When(a.GenericKind, {
  group: "pepr.dev",
  version: "v1",
  kind: "Unicorn",
})
  .IsCreated()
  .WithName("example-1")
  .Watch(() => Log.info("Unicorn Created"));
```

Seems like the watch URL is being called with GenericKind, if we do the GVK map and it is undefined than there is more work to do in order to know what to watch.

```bash
[08:50:49.696] DEBUG (95315): Watch event network_error received. watch connect failed: 404 Not Found.
```

**Comment by cmwylie19** [comment]
This may not be a problem, when this is tested let's ensure the CRD is first applied to the cluster 


```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: unicorns.pepr.dev
spec:
  group: pepr.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                counter:
                  type: number
  scope: Namespaced
  names:
    plural: unicorns
    singular: unicorn
    kind: Unicorn
```
