### ISSUE TITLE
Use Latest Version of Pepr in Generated Zarf package

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/pepr#184]
Running `npx pepr build` generates a `zarf.yaml` that has the Pepr image version hardcoded to `v0.0.1`

```
kind: ZarfPackageConfig
metadata:
  name: pepr-c8b24d7e-482b-5912-9177-0287a248ca83
  description: 'Pepr Module: uds pepr POC'
  url: https://github.com/defenseunicorns/pepr
  version: 0.0.1
components:
  - name: module
    required: true
    manifests:
      - name: module
        namespace: pepr-system
        files:
          - pepr-module-c8b24d7e-482b-5912-9177-0287a248ca83.yaml
    images:
      - ghcr.io/defenseunicorns/pepr/controller:v0.0.1
```
