### ISSUE TITLE
Incorrect MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#201]
When using `a.GenericKind` Pepr [assumes](https://github.com/defenseunicorns/pepr/blob/419510839102ce34268230d48f9648fb0d1e2f05/src/lib/k8s/webhook.ts#L217) the plural for resources. We need logic to check if the kind.kind ends in y, and if so, add `ies` instead of `s`

Example of error:

in Capability
```javascript
When(a.GenericKind, {
  group: "source.toolkit.fluxcd.io",
  version: "v1beta2",
  kind: "GitRepository",
})
```

Resulting MutatingWebhookConfiguration
```yaml
  - apiGroups:
    - source.toolkit.fluxcd.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - gitrepositorys
```

expectation
```bash
gitrepositories                   gitrepo            source.toolkit.fluxcd.io/v1beta2       true         GitRepository
```

No biggy, i can work around this and I will pick up this PR.
