### ISSUE TITLE
`npx pepr crd generate` is creating an array of status conditions when the variable is an object

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#2134]
### Describe what should be investigated or refactored

Given the following, the resulting CRD should have the condition equal to a single object
```ts
export interface WebAppStatus {
  /*
   * Conditions describrent state
   */
  conditions?: WebAppStatusCondition;
}

export const details = {
  plural: "webapps",
  scope: "Namespaced",
  shortName: "wa",
};

export type WebAppStatusCondition = {
  /**
   * lastTransitionTime is the last time the condition transitioned from one status to another. This is not guaranteed to be set in happensBefore order across different conditions for a given object. It may be unset in some circumstances.
   */
  lastTransitionTime: Date;
  /**
   * reason contains a programmatic identifier indicating the reason for the condition's last transition. If this value is empty, it should be treated as "incomplete".
   */
  reason: string;
  /**
   * status of the condition, Pending, Ready, Failed
   */
  status: string;

  /**
   * observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance.
   */
  observedGeneration: number;
};

```

**Comment by cmwylie19** [comment]
since Kubernetes is processing status as conditions and this is an alpha feature I am going to leave as it for now

```yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-08T20:30:48Z"
    lastUpdateTime: "2025-05-08T20:30:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-08T20:30:46Z"
    lastUpdateTime: "2025-05-08T20:31:06Z"
    message: ReplicaSet "a-57b96cb858" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
```
