### ISSUE TITLE
Docs workflow should only trigger on a push or pr to main branch 

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#423]
### Environment
Device and OS:
App version:
Kubernetes distro being used:
Other:

Docs workflow should only trigger on a push or pr to main branch  

```
name: docs

# declare default permissions
permissions: read-all

on:
  # enable manual run via GitHub UI
  workflow_dispatch:
  
  # enable triggering on docs file changes
  # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-paths-for-pull-request-or-push-events
  push:
    branches: ["main"]
    paths: ["docs/**.md"]

  pull_request:
    branches: ["main"]
    paths: ["docs/**.md"]
```
### Steps to reproduce
1. Push Updated docs to a branch that is not main 

### Expected result
1. The docs workflow not to react 

### Severity/Priority
low 
### Additional Context
Add any other context or screenshots about the technical debt here.
