### ISSUE TITLE
Mutation annotation needs sanitization

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#730]
### Environment

Mutation annotation needs sanitization 
```bash
The Namespace "pepr-demo" is invalid: metadata.annotations: Invalid value: "b9ea57fe-e4f9-55b1-9bdc-0dc6eeb49aa0.pepr.dev/hello pepr": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

### Steps to reproduce
Define the capability name with a space

```ts
export const HelloPepr = new Capability({
  name: "hello pepr",
  description: "A simple example capability to show how things work.",
  namespaces: ["pepr-demo", "pepr-demo-2"],
});
```
Create a mutation

```yaml
k apply -f -<<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: pepr-demo
  labels:
    keep-me: please
    remove-me: please
EOF
The Namespace "pepr-demo" is invalid: metadata.annotations: Invalid value: "b9ea57fe-e4f9-55b1-9bdc-0dc6eeb49aa0.pepr.dev/hello pepr": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

### Expected result

Mutation annotation to be kubernetes safe

### Additional Context
Add any other context or screenshots about the technical debt here.
