### ISSUE TITLE
Tuning Envoys: Adjust Istio Idle Timeout in UDS Core

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#847]
Related to #745 

With regard to the Kubernetes Watch flakiness it was suggested to try adjusting the `idleTimeout` in Istio to see if that plays any role keeping the connections alive. 

Background: The `idleTime` determines the duration a connection can be idle before being terminated by the proxy. 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: timeout-test
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY # EVERYWHERE!
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: "3h" # Increased from 1 hour
```

Definition of done:
- [x] Deploy UDS Core with Pepr <= `0.31.0` (Pre-Informer to make sure results are not skewed)
- [x] Crank up neuvector the CronJob to run every minute  
- [x] Deploy this `EnvoyFilter` for the whole mesh
- [x] Document and present results 

CC: @blancharda 

Related External Issue: https://github.com/istio/istio/issues/50089
