### ISSUE TITLE
Look into TS Version of Pepr, it may not be getting updated

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#848]
There is a possibility that the TypeScript version of Pepr is not getting updated. We need to verify and check to ensure we are using the latest stable version. 

- [ ] Test that you can still use `npx pepr ...`
- [ ] Look at size of controller image

**Comment by schaeferka** [comment]
It appears that the issue isn't isolated to TypeScript. All of the `peerDependencies` are not updating.

**Comment by cmwylie19** [comment]
> It appears that the issue isn't isolated to TypeScript. All of the `peerDependencies` are not updating.

Interesting, we will want all of our dependencies up to date. I wonder if there is something to do in the `dependabot.yaml` to include the `peerDepedencies`?

https://github.com/defenseunicorns/pepr/blob/main/.github/dependabot.yml

**Comment by schaeferka** [comment]
Two initial options to explore:

1. Adding something like this to the `groups` in `dependabot.yml`:

```yaml
      peer-dependencies:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "commander"
          - "esbuild"
          - "eslint"
          - "node-forge"
          - "prettier"
          - "prompts"
          - "typescript"
          - "uuid"
 ```

2. Adding the `peerDependencies` to the `devDependencies` so that they'll get picked up there.
