### ISSUE TITLE
`npx pepr build --registry "Iron Bank"` missing v 

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#888]
### Environment
Device and OS:
App version:
Kubernetes distro being used:
Other:

### Steps to reproduce
1. `npx pepr build --registry "Iron Bank"
2. add `imagePullSecret` to podSpec
3. deploy

```
state:
        waiting:
          message: Back-off pulling image "registry1.dso.mil/ironbank/opensource/defenseunicorns/pepr/controller:0.32.0"
          reason: ImagePullBackOff
```

### Expected result

```
state:
        waiting:
          message: Back-off pulling image "registry1.dso.mil/ironbank/opensource/defenseunicorns/pepr/controller:v0.32.0"
          reason: ImagePullBackOff
```
### Additional Context
Add any other context or screenshots about the technical debt here.
