### ISSUE TITLE
should default env for deployments to pepr_watch_mode

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#966]
### Describe what should be investigated or refactored. 

For the admission and the watcher deployment.  

```yaml
                env:
                  {{- toYaml .Values.watcher.env | nindent 12 }}
                  - name: "PEPR_WATCH_MODE"
                    value: "true"
```

### Links to any relevant code
`/src/lib/assets/helm.ts`

### Additional context
Add any other context or screenshots about the technical debt here.
