### ISSUE TITLE
look at consolidating genEnv into yaml.ts function so we use the same function when generating manifests.yaml and helm 

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#989]
### Describe what should be investigated or refactored
look at consolidating genEnv into yaml.ts function so we use the same function when generating manifests.yaml and helm. Also, remove the ability to override `PEPR_WATCH_MODE` by setting it in the helm deployments last.

```yaml
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: example-container
      image: nginx
      env:
        - name: MY_ENV_VAR
          value: "first-value"
        - name: MY_ENV_VAR
          value: "second-value"
 > EOF
```

```bash
Warning: spec.containers[0].env[1].name: duplicate name "MY_ENV_VAR"
pod/example-pod created
> k exec -it example-pod -- env 
MY_ENV_VAR=second-value
```

![Image](https://github.com/user-attachments/assets/926a17fc-e3ae-4b99-a9ab-fd3bc586133b)
